### PR TITLE
Postgresql/bigserial primary key only

### PR DESCRIPTION
**Pull request by phaazon**

### CODE REVIEW

**Comment by phaazon** [comment]
I’m currently testing and investigating test failures.

**Comment by phaazon** [comment]
```selda_test-# from INFORMATION_SCHEMA.COLUMNS where table_name = 'Foo';
 column_name | data_type | character_maximum_length
-------------+-----------+--------------------------
 foo_id      | bigint    |
 foo_name    | text      |
 foo_bar     | bigint    |```

Oops, fail :)

**Comment by phaazon** [comment]
Hm seems like it’s always `bigint`, even on `bigserial`.

**Comment by phaazon** [comment]
(this is so confusing)

**Comment by phaazon** [comment]
Nevermind, it works on my psql.

**Comment by phaazon** [comment]
Great success \o

**Comment by valderman** [comment]
Nice!

**Pull request merged**
