### PR TITLE
Set the current schema when connecting.

### PR DESCRIPTION
**Pull request by phaazon**
This is only available for PostgreSQL for now.

### CODE REVIEW

**Comment by valderman** [comment]
Let's merge this since it won't disrupt things for anyone who isn't using it anyway, but it would be nice if there was an automated way to check that this works as intended. Not sure how to go about that though, since I guess it'd require automatically planting a schema somewhere in the test environment?

**Comment by phaazon** [comment]
Yeah it would. I tested with my application, it works, yet, a good test would be great.

You can simply test by playing the `tryCreateTable` function and inspect the content of the database afterwards: the tables are scoped in the schema.

**Comment by phaazon** [comment]
Also, now that I think about it, is there any things against SQL injections? That patch might have introduced one!

**Comment by valderman** [comment]
I don't really think injection is a concern here. If you give outside actors _any_ chance to modify the connection info object, you already have a big problem. Also, `SET search_path TO $1` doesn't seem to work anyway (unless I'm being extra stupid today), so I think it's fine to leave it as it is. I did add some quotes around the schema though, to prevent accidental breakage from things like periods.

**Pull request merged**
