### PR TITLE
add mysql backend

### PR DESCRIPTION
**Pull request by kuribas**
I created a mysql backend.  It is working, but not extensively tested.  There are some things which need attention.

- I am using Int for bigint, but Int isn't guaranteed to have 64 bits.  So it may truncate 64 bit values on some systems.  I propose using int64 and word64 instead.  That would work portably with many systems.
- Date conversion isn't efficient with prepared statements, because I need to parse the string, then convert it to a binary format.  It would be easier if selda would use a binary format for dates (for example UTCTime etc..)  That would require however that all backends are adapted.

### CODE REVIEW

**Comment by kuribas** [comment]
The tables can be created now.  There are still problems:

- cast cannot take any type, it has to pick from a limited set of types.  The type can also not be quoted.  
- Text columns cannot be used in places with indexes, so it should use varchar(3000) instead.  However this depends on the indexes, and the pretty printer doesn't have that information.
- some column aliases are duplicates, and mysql doesn't allow that.

There are others, but these are the most occuring.

**Comment by valderman** [comment]
What's the best way forward with this? I'm open to making quite sweeping changes to the backend API if necessary (next release will require backend changes anyway), so a binary format for dates is definitely doable. If you need any other backend changes, or anything specific on my part, let me know and I'll see what I can do.

As for the specific issues:
* Do you have an example of a query where you're seeing duplicate aliases? This isn't supposed to happen and if it does we need to fix it. May be related to #28, which I've never been able to reproduce before.
* MSSQL also has this limitation, so I'm thinking we may want to add a `VarChar :: Int -> *` type for strings up to a known length, and disallow indexing on full text and binary columns altogether.
* The limitations on cast sound a bit annoying, but I think we can get around it. Not quoting the type is easily fixed, and cast is marked as unsafe anyway so it's no big deal if it does weird things on MySQL. The one thing we need to be careful about is finding where it's used with disallowed types by other, safe, primitives and investigate whether it could be replaced by something else there.

**Comment by kuribas** [comment]
I am not currently working on this, as it appears to be much more work then I initially thought.  It also seems that selda isn't really designed around using existing databases, which is our usecase. However I think this implementation is a step in the good direction, so perhaps someone else may want to continue this.  
As to the issues:

- I saw them when running the tests
- yes, that may work
- yeah, this seems to be really something peculiar from mysql.  It's annoying but necessary to work around it.

**Comment by TomMD** [comment]
Perhaps this should be closed? Built, errors encountered, abandoned.  No shame it it, this is how development goes after all.

**Pull request closed without merging**
